import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar.jsx";
import Providers from "./components/Providers.jsx";
import { auth } from "./auth";
import { AuthProvider } from "./context/AuthContext";
import { findUsernameFromEmail } from "./lib/data.js";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await auth();
  let username = null;

  if (session?.user?.email) {
    username = await findUsernameFromEmail(session.user.email);
  }

  return (
    <html lang="en">
      <body className={`${inter.className} px-5 pt-8`}>
        <div className="bg-[#F9F9F9] border-[#E4E4E7] border-1 rounded-t-xl">
          <Providers>
            <AuthProvider>
              <Navbar username={username} />
              {children}
            </AuthProvider>
          </Providers>
        </div>
      </body>
    </html>
  );
}
